name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Verify files exist
        run: |
          ls -la
          [ -f Dockerfile ] || { echo "Dockerfile missing"; exit 1; }
          [ -f runtests.sh ] && chmod +x runtests.sh

      - name: Build Docker image
        run: docker build -t my_hub:latest .

      - name: Run tests
        run: |
          if [ -f runtests.sh ]; then
            ./runtests.sh || exit 1
          else
            echo "No tests to run"
          fi

      - name: Save Docker image
        run: docker save my_hub:latest -o my_hub.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: my_hub.tar

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load -i my_hub.tar

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKER_USERNAME }}" \
          --password-stdin

      - name: Verify Docker Hub credentials
        run: |
          echo "Trying to push as: ${{ secrets.DOCKER_USERNAME }}"
          docker info | grep Username

      - name: Tag and push image
        run: |
          docker tag my_hub:latest ${{ secrets.DOCKER_USERNAME }}/my_hub:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my_hub:latest