name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to v4

      - name: Build Docker Image
        run: docker build -t my_hub:latest .

      - name: Save Docker Image as Tarball
        run: docker save my_hub:latest -o my_hub.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: my_hub.tar

      - name: Run Container and Execute Tests
        run: docker run --rm my_hub:latest ./runtests.sh

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to v4

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: docker load -i my_hub.tar

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKER_USERNAME }}" \
          --password-stdin

      - name: Tag Docker Image
        run: docker tag my_hub:latest otayalaa/my_hub:latest

      - name: Push Docker Image
        run: docker push otayalaa/my_hub:latest